using CoreLayer.BaseEntities;
using Microsoft.EntityFrameworkCore;
using RepositoryLayer.Context;
using RepositoryLayer.Repositories.Abstract;
using System.Linq.Expressions;

namespace RepositoryLayer.Repositories.Concrete
{
    #region Why we add new in the last
    // 'new()' constraint ensures that the generic type T has a parameterless constructor.
    // This allows creating new instances inside the repository (e.g., new T()) when needed.
    #endregion
    public class GenericRepositories<T> : IGenericRepositories<T> where T: class, IBaseEntity, new()
    {
        private readonly AppDbContext _context;
        private readonly DbSet<T> _dbSet; // Short cut to _context.Set<T>().

        public GenericRepositories(AppDbContext context)
        {
            _context = context;
            //Auto assign(_dbSet) when any class take obj from GenericRepo.
            _dbSet = _context.Set<T>(); // 
        }



        #region Why we use Async here?
        // We use AddAsync here because some properties (like RowVersion or Identity columns) 
        // are automatically generated by the database, 
        // and EF Core needs to read their values after inserting the new entity.
        #endregion
        public async Task AddEntityAsync(T entity)
        {
            await _dbSet.AddAsync(entity);
        }

        // its not necessary to use Async here 
        public void UpdateEntity(T entity)
        {
            _dbSet.Update(entity);
        }

        public void DeleteEntity (T entity)
        {
            _dbSet.Remove(entity);
        }

        #region Why we return IQueryable here ?
        // We return IQueryable here to allow deferred execution and further query composition.
        // This lets EF Core translate any additional filters (e.g., Where, OrderBy) into SQL queries,
        // so filtering happens in the database instead of in memory — improving performance and flexibility.
        #endregion
        public IQueryable<T> GetAllEntityList()
        {
            return _dbSet.AsNoTracking().AsQueryable(); // AsQueryable is not necessary here but we add it any way. 
        }

        #region Why we use Expression?
        // Expression: Translates the condition into an SQL query,
        // allowing EF Core to execute filtering in the database for better performance.
        #endregion
        public IQueryable<T> Where(Expression<Func<T,bool>> predicate)
        {
            return _dbSet.Where(predicate);
        }

        public async Task<T> GetEntityByIdAsync(int id)
        {
            return await _dbSet.FindAsync(id);
        }

    }
}
